apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      service: sampleappsvc
  template:
    metadata:
      labels:
        app: sampleapp
        service: sampleappsvc
        App: nginx
        Environment: test
        Owner: just-me
    spec:
      containers:
        - name: buggy
          image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:$TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: sampleappsvc
  labels:
    app: sampleapp
    service: sampleappsvc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: sampleappsvc

